name: 'Deploy to Caprover'
description: 'Github Action for deploying your app to Caprover.'
author: 'Caprover Contributors'

inputs:
  server:
    description: 'Captover server URL, i.e. https://captain.apps.your-domain.com.'
    required: false
  token:
    description: 'App Token'
    required: true
  app:
    description: 'App Name'
    required: true

runs:
  using: 'docker'
  image: 'docker://ghcr.io/captover/deploy-from-github:main'
  env:
    server: ${{ inputs.server }}
    app: ${{ inputs.app }}
    token: ${{ inputs.token }}
